### ISSUE TITLE
Masarah project Idea

### ISSUE THREAD

**Issue by Masarsah** [WDI-HoneyBadger/Project1-Prompt#2]
Project idea: I want to make a Sudoku  game like puzzle where you can figure the missing number.
How it works: 1 players complete problem with number missing 
my wireframes are here: https://wireframe.cc/h7R0uK

**Comment by trevorpreston** [comment]
This sounds like a good idea.  How would the board work?  Do they click on a square and type the number?  Will you have some way of checking to make sure that they can't enter a number that is already in the row?  How will you decide what numbers are on the board?

**Comment by Masarsah** [comment]
How would the board work? 
Board will work as  table 
Do they click on a square and type the number?    
Chose number 
Will you have some way of checking to make sure that they can't enter a number that is already in the row?  Using map
How will you decide what numbers are on the board?
Using array each table should have max of 10

it is my favorite game I really went to built it currently I’ll focus on easy one

**Comment by trevorpreston** [comment]
ok, so are you still thinking about doing this?

**Comment by Masarsah** [comment]
yes sure

**Comment by trevorpreston** [comment]
Ok sounds good.  Good luck!  This is a pretty challenging one :)
