### ISSUE TITLE
May's Idea: Connect 4

### ISSUE THREAD

**Issue by MayMo7a** [WDI-HoneyBadger/Project1-Prompt#4]
Project idea: 2 players game, 2 colors discs which the players take turns dropping one colored disc into a 7*6 grid. 
Game objective: to be the first to form a horizontal, vertical, or diagonal line of four of your own discs. Wireframes sketches are here:
![img-2889](https://user-images.githubusercontent.com/10823118/48977947-5aec9100-f0b5-11e8-9eb2-4765a28dd65f.JPG)

**Comment by trevorpreston** [comment]
Connect 4 is a great project.  Good luck!
